### ISSUE TITLE
tuist application

### ISSUE THREAD

**Issue by jeonghomoon** [jeonghomoon/tuist-generator#1]
## Description
- Tuist를 사용하여 Xcode 프로젝트의 생성, 유지 관리 및 상호 작용을 용이하게 할 수 있습니다.
- 모듈화된 프로젝트를 편하게 관리하고, 소스 코드 형상관리로 인해 발생하는 문제를 없애기 위해 Tuist를 도입합니다.

## TODO
- [x] zip 폴더에 tuist를 초기화 해야합니다. 이때 만들어지는 .gitignore을 현재와 비교하여 수정합니다.
- [x] 프로젝트들을 관리하기 위한 Workspace 관련 설정을 추가해야합니다.
- [x] 예제 코드를 제거하고 어플리케이션 전반을 제어하기 위한 Application 프로젝트를 추가해야합니다.
- [x] 어플리케이션의 라이프사이클을 관리하는 AppDelegate, SceneDelegate를 추가해야합니다.
- [x] AppDelegate, SceneDelegate 등 어플리케이션 단의 코드를 테스트할 파일을 추가해야합니다.
- [x] 아이콘과 로고에 대한 정보를 저장하는 Assets와, 런치 스크린으로 사용할 LaunchScreen 파일을 추가해야합니다.
- [x] Info.plist를 Manifest를 통해 직접 관리하지 않기 위해 기정의된 Info.plist 파일을 추가해야합니다.

## Environment
macOS: Monterey 12.5.1, Apple M1
iOS: 15.5, iPhone 13 mini
IDE: Xcode 13.4.1

Related:
