### ISSUE TITLE
tuist feature template

### ISSUE THREAD

**Issue by jeonghomoon** [jeonghomoon/tuist-generator#3]
## Description
- 각 Feature 별로 프로젝트를 나눈다면 빌드 속도 감소와 협업에 용이합니다.
- Feature 프로젝트들의 경우 유사한 구조를 가집니다.
- Tuist의 scaffold를 이용하여 이를 템플릿화 하여 손쉽게 구성할 수 있습니다.

## TODO
- [x] 프로젝트를 샘플 앱 역할을 할 타겟과 [해당 아키텍처](https://developer.android.com/jetpack/guide?hl=ko)를 참고한 UI, Domain, Data 타겟으로 나눠야합니다.
- [x] 샘플 앱의 경우 하나의 앱이기 하기 때문에 ZipApp과 동일하게 Source, Resource, Supports, Tests 형태로 구성해야합니다.
- [x] UI의 경우 Sources(AuthViewController), Resources(Assets, Nib, ...), Tests 형태로 구성해야합니다.
- [x] UI의 경우 리소스 파일이 포함되기 때문에 makeFrameworkTargets 메소드를 수정해야합니다.
- [x] 샘플 앱에서 최초로 띄워줄 UI의 ViewController를 rootViewController로 지정해야합니다.
- [x] Domain의 경우 별도의 리소스 파일이 필요 없기 때문에 Sources, Tests 형태로 구성해야합니다.
- [x] Data도 Domain과 동일하게 Sources, Tests 형태로 구성해야합니다.

## Environment
macOS: Monterey 12.5.1, Apple M1
iOS: 15.5, iPhone 13 mini
IDE: Xcode 13.4.1

Related:
